### ISSUE TITLE
NodeJS packages do not follow the Flake output schema

### ISSUE THREAD

**Issue by danth** [DavHau/dream2nix#39]
Nix expects flakes to export their packages as `packages.«system».«name»`, but dream2nix exports them as `packages.«system».«name».«version»`:

https://github.com/DavHau/dream2nix/blob/47287126d8ea4c5b586f38e3044f31af7578cccb/src/builders/nodejs/node2nix/default.nix#L117

This causes the `nix flake show` command to fail with `error: expected a derivation`.

**Comment by DavHau** [comment]
Thanks for looking into this. The design is not finalized yet. I totally agree this must be changed. I currently have 2 alternative schemas in mind. Let me know about your opinion.

Alternative 1 (package name and version in attribute name):
```nix
packages.{system} = {
  foo-latest = {latest-foo-package};
  "foo-1.0.0" = ...;
  "foo-1.2.0" = ...;
}
```

Alternative 2 (one attribute for latest package; other versions inside passthru of latest):
```nix
packages.{system} = {
  foo = {latest-foo-package};
  foo."1.0.0" = ...;
  foo."1.2.0" = ...;
}
```

Alternative 1 makes all attributes clearly visible on the top level.
Alternative 2 is better for automation tools which want to simply list all available versions for a specific package.
Maybe we should do a mix of 1 & 2.

**Comment by danth** [comment]
I prefer the second alternative because it is more obvious which is the canonical version of the package. Also, it avoids exporting the same derivation under two different attributes (`foo-latest` and `foo-1.2.0` in this example).

The first schema would be more suitable for the `checks` output, if you choose to provide that, as it means each individual version is tested by `nix flake check`.

**Comment by DavHau** [comment]
I did it now a bit different. Alternative 2 has the problem that the other version attributes will be mixed with all other stuff whcih the derivation passes through. This would be bad for automation. Therefore I went for:
Alternative 3:
```nix
packages.{system} = {
  foo = {latest-foo-package};
  foo.versions."1.0.0" = ...;
  foo.versions."1.2.0" = ...;
}
```
